# Generated by Django 3.1.4 on 2020-12-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwdgen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repository',
            new_name='Password',
        ),
        migrations.AlterModelOptions(
            name='password',
            options={'ordering': ['-created'], 'verbose_name': 'Password', 'verbose_name_plural': 'Passwords'},
        ),
    ]
