# Generated by Django 3.1.4 on 2021-01-04 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pwdgen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='password',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('owner', 'name')},
        ),
    ]
