# Generated by Django 3.1.4 on 2021-01-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwdgen', '0004_auto_20210101_2339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='password',
            unique_together={('category', 'name')},
        ),
    ]
