# Generated by Django 3.1.4 on 2021-01-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdgen', '0005_auto_20210102_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='slug',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
