version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - 5432:5432
    volumes:
      - ../pg_data:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: .
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: "${DJANGO_SETTINGS_MODULE}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DATABASE_HOST: "${DATABASE_HOST}"
    ports:
      - 8000:8000
    volumes:
      - ./:/futurepassword
    depends_on:
      - postgres
    restart: always
