version: '3.7'

services:
    postgres:
        image: postgres:latest
        container_name: futurepassword-db
        env_file:
            - ./.env.dev.db
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        restart: always

    web:
        container_name: futurepassword
        tty:
            true
        build:
            context: .
            dockerfile: Dockerfile
        command:
            bash -c "python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - ./.env.dev
        ports:
            - 8000:8000
        depends_on:
            - postgres
        restart: always
